### ISSUE TITLE
Architecting Attribution: expanding the scope of academic credit

### ISSUE THREAD

**Issue by kristiholmes** [ResearchObject/ro2019#1]
### Authors

* Kristi Holmes - Northwestern University, https://orcid.org/0000-0001-8420-5254 (intended presenter)
* Nicole Vasilevsky - Oregon Health & Science University, https://orcid.org/0000-0001-5208-3432
* Marijane White - Oregon Health & Science University, https://orcid.org/0000-0001-5059-4132       
* Matthew Brush - Oregon Health & Science University, https://orcid.org/0000-0002-1048-5019 
* Lisa O’Keefe - Northwestern University, https://orcid.org/0000-0003-1211-7583 
* Karen Gutzman - Northwestern University, https://orcid.org/0000-0001-6331-4451 
* Melissa Haendel - Oregon Health & Science University, https://orcid.org/0000-0001-9114-8737 

### Keywords

* attribution 
* credit 
* ontology 
* promotion 
* tenure 
* research object 

### Preprint

https://zenodo.org/record/3334688#.XSstgnt7lp8

### Abstract

Traditional metrics for scholarship typically only measure publication records and grants received. However scholarly contributions can extend well beyond these traditional contributions. In order to properly give attribution for scholarship, we need improved mechanisms for recognizing and quantifying these efforts. We aim to develop a computable system to better attribute scholars for the work they do. 

_Full submission at https://zenodo.org/record/3334688#.XSstgnt7lp8_

**Comment by stain** [comment]
Thank you for submitting to RO2019's open peer review process. We will shortly be assigning members from the [Programme Committee](https://researchobject.github.io/ro2019/#program-committee) to review.

Feel free to respond to reviewers comments and to update the submission if needed. 

**Tip:** Anyone is welcome to add an informal review below using GitHub comments; as an author perhaps you would volunteer to review [one of the other open submissions](https://github.com/ResearchObject/ro2019/issues)? 

Reviewers, please copy this review form and add as a comment. You don't need to use this form if you are not assigned from the PC.

```markdown
## Quality of Writing
_Is the text easy to follow? Are core concepts defined or referenced? 
Is it clear what is the author's contribution?_

(delete as appropriate)
* excellent / good / fair / poor

## Research Object / Zenodo

_URL for a Research Object or Zenodo record provided?
   Guidelines <http://researchobject.org/ro2019/submitting> followed?
   Open format (e.g. HTML)?
   Sufficient metadata, e.g. links to software?
   Some form of Data Package provided?
   Add text below if you need to clarify your score._

(delete as appropriate)
* none (e.g. only abstract in easychair/github)
* basic (e.g. Zenodo with PDF and minimal metadata)
* sufficient (e.g. HTML, detailed Zenodo metadata)
* good (followed guidelines, demonstrating own format, related resources included, but some details missing)
* excellent (e.g. followed all guidelines, complete metadata or RO-like research data package, linked data, provenance)

## Overall evaluation
_Please provide a brief review, including a justification for your scores. 
Both score and  review text are required._

(delete as appropriate)
* strong reject
* reject
* weak reject
* borderline 
* weak accept
* accept
* strong accept
```

For confidential remarks or questions about the peer-review process, contact ro2019@easychair.org

**Comment by ptsefton** [comment]
I will review

**Comment by stain** [comment]
Reminder that review of this abstract is due tomorrow Friday 2019-07-26. 

We're looking for one more volunteer! Perhaps @rapw3k, @eocarragain, @josemanuelgp or @ocorcho  could have capacity..?

**Comment by stain** [comment]
Review deadline is today - any volunteers from @ResearchObject/ro-crate team?

**Comment by rapw3k** [comment]
## Quality of Writing

* excellent 
abstract is easy to follow, presents a good motivation and introduces clearly the key contribution

## Research Object / Zenodo

* sufficient (e.g. HTML, detailed Zenodo metadata)

## Overall evaluation
* accept

this abstract introduces a computational approach to attribution, which considers different types of roles and contributions made to a research or scholarship work, beyond the traditional publication counts and grant dollars received.  In particular, the abstract discusses briefly the Contributor Role Ontology (CRO) as the underlying model to implement such system. This model was created based on the requirements gathered from different stakeholders (e.g., scholars, researchers, publishers, funders, and librarians), and its goal is to support the collection, provision and exchange of contribution metadata, which can then be used for visualisation, querying and computational analyses. Additionally, authors are now on the process to build a model to represent the relationship between an entity, an agent that contributes to it, and the contributions role, whereas the entity can be any research artefact/product (physical or digital). Hence, this model can be also applied to any type of research object (RO). 
So, this work is quite relevant to the research object community and related models. There are some points to discuss. First, authors didn’t mention how they are building this new model; however, it seems that PROV-O could be a very relevant starting point (base) for such model. PROV-O models different relations between an entity, the agent responsible for the creation of such entity, and the activity used or that generated such entity. So, it would be nice to hear authors thoughts about this. Second, this model and CRO could be nicely integrated/connected to the RO model ontologies. In particular, the RO evolution ontology (roevo) [1], would be the perfect connection point, as it models changes to the research object. These changes, are basically contributions, which are made by the different stakeholders involved in the research/scholarship work. Additionally, roevo is already based on PROV-O, so the connection would be very straightforward and useful. And even thought authors didn’t mention such connections, it would be interesting to hear their thoughts about this during the workshop.

**Comment by dgarijo** [comment]
## Quality of Writing
 * good 

## Research Object / Zenodo
* sufficient (e.g. HTML, detailed Zenodo metadata)

## Overall evaluation
* accept

This talk describes a community initiative with the goal of capturing scientific contributions.

I think the talk is very relevant for the workshop and the conference, as Research Objects are often created collaboratively and it becomes crucial to give proper credit to authors. As the authors mention, this initiative will only be possible with the involvement of the academic community. There are many ways of recording credit automatically, and I would like to know if the authors plan on capturing them in their framework, or just rely on author annotation. Do the authors plan on doing any long term study on the impact of these kind of initiatives in a researcher's career? Maybe that would be a nice selling point for the community to get more engaged.

As a side comment, I find odd that the contributor role ontology is not derreferenceable (just returns plain rdf), and I wasn't able to find documentation in human-readable format. In addition, shouldn't the ontology reflect who contributed to it and how? I only see the same creator for all properties.

**Comment by kristiholmes** [comment]
Thanks very much to @dgarijo and @rapw3k for your thoughtful comments.  Some of your remarks reflect ongoing questions/issues that have come up on our project team, so this is incredibly helpful.  Thanks for your input and for the opportunity to submit this abstract for consideration. Cheers!

**Comment by stain** [comment]
Dear @kristiholmes et al:

I am pleased to say that, given the reviewer comments, your submission has been **accepted** for oral presentation at [RO2019](https://researchobject.github.io/ro2019/).

You are invited to present a _10 minute talk_, followed by joint Q&A at end of the session.

You are also welcome to bring along a poster for the informal RO2019 poster session (which may cover work not reflected in this submission).


**Note**: All RO2019 presenters must _register_ and _attend_ the workshop at [eScience 2019](https://escience2019.sdsc.edu/) - please take care that you [register](https://escience2019.sdsc.edu/registration) with the  **Conference & Workshop** option to join the RO2019 workshop on Tue 24 Sept 2019.

Registration fees applies. Note that the IEEE eScience _early-bird registration_ discount expires **this Monday** - although we are negotiating with the eScience organizers to possibly extend this for presenters. A [PhD and Early career grant](https://escience2019.sdsc.edu/grant) is also available.

**Comment by stain** [comment]
Dear @kristiholmes et al,

As an accepted author at the RO2019 workshop we would like to remind you that at least one of the authors must be **registered** and **attend** the workshop at IEEE eScience 2019.

Please indicate here if the intended speaker(s)  differ from your initial submission.


eScience registration is at: <https://escience2019.sdsc.edu/registration>


We are pleased to inform you that, following our request, the availability of the eScience **early bird discount** has been extended until Monday 5 August 2019.


To [register](https://escience2019.sdsc.edu/registration), please select the _"Conference & Workshops"_ option, as the RO2019 workshop is on the Tuesday.


As a presenter, make sure you select:

* **Type:** "PRESENTER: Conference & Workshops", 
* **Session:** Workshop
* **Paper Number:** RO-13
* **Paper title:** Architecting Attribution: expanding the scope of academic credit

(It is possible to do _"Add Additional Paper/Poster"_ if you have other accepted eScience contributions - note that you do NOT need to use this for any RO2019 posters).

We look forward to seeing you in San Diego!

-- 
Stian Soiland-Reyes
on behalf of the RO2019 chairs

**Comment by stain** [comment]
Dear @kristiholmes et al,

We are looking forward to hearing your submission presented at the RO2019 workshop in San Diego next week!

You will find the slot for your talk RO-13 in the workshop schedule:
<http://researchobject.org/ro2019/schedule>

Please let us know if you require a different time slot, or the indicated speaker has changed.


## Tweets

Feel free to tweet before/during/after the workshop!

We will use the hashtags [#ResearchObjects](https://twitter.com/hashtag/ResearchObjects) [#eScience2019](https://twitter.com/hashtag/eScience2019) 
(plural s)


## Slides

If you are presenting slides, we would appreciate if you are able to upload them here:
<https://www.dropbox.com/request/B1EDF6bNOULm9wS5S7Z7>

Format can be html, pdf, pptx, odp (we can convert to PDF)

I understand you may not have your slides ready yet, but we would appreciate if they are uploaded *before* your session start.


If your slides are web-based or already on Zenodo,  submit their URL here:
<https://github.com/ResearchObject/ro2019/issues/new/choose>

The resolution of the projector is 1920x1080 (16:9 widescreen).

Tip: If you use Twitter, include `@YourUsername` in the footer!

After the workshop we will upload the slides to Zenodo as CC-BY, please let us know if you require your slides to not be made public. 


## Zenodo 

You may also want to update your Zenodo record to augment your paper/abstract with the slides as a PDF - the DOI links from the Schedule page always to go the latest Zenodo update.

We have noticed some uploads have a mismatch of the  author lists. This might be a good time to check the metadata: 
<http://researchobject.org/ro2019/proceedings>


## Posters 

As noted earlier, all accepted speakers are welcome to bring along posters for the "informal" poster session, even if  the poster is not directly related to the accepted talk.

The poster should however be relevant to the aims of the [RO2019 workshop](http://researchobject.org/ro2019/) and not be a pure commercial.

If you bring a poster, please use the 10:05-10:30 coffee break to hang it in the room.

Posters should be no larger than 35” (0.89m) wide by 48” (1.2 m) tall with portrait-style orientation. 

Poster presenters are welcomed to do a 2 minute lightning talk during the "unconference" session.


## Unconference and collaborative notes
  
We are welcoming suggestions for activities during the afternoon unconference session, e.g.:
lightning talks, posters, demos, breakouts, discussions

Please help add ideas, comments and suggestion in the _Collective notes for RO2019 workshop_ <https://s.apache.org/ro2019>

You may also use this document for adding URLs and questions during the presentation sessions.
