### ISSUE TITLE
Citation and Research Objects: Toward Active Research Objects

### ISSUE THREAD

**Issue by danielskatz** [ResearchObject/ro2019#2]
Citation and Research Objects: Toward Active Research Objects

### Authors

* **Name**: Daniel S. Katz
* **Affiliation**: University of Illinois at Urbana-Champaign
* **ORCID**: http://orcid.org/0000-0001-5934-7525

### Keywords

* software citation
* data citation
* Research Objects

### Preprint

https://doi.org/10.5281/zenodo.3338176

### Abstract

This extended abstract, submitted to the Workshop on Research Objects 2019 (RO2019), being held in conjuction with the 15th International Conference on eScience (eScience 2019), discusses the state of citation for software and for data, and explains challenges in citing more complex research objects, including Research Objects. It includes a proposal for how current Research Objects and their contents can be cited, and additionally proposes Active Research Objects to make this easier.

**Comment by stain** [comment]
Thank you for submitting to RO2019's open peer review process. We will shortly be assigning members from the [Programme Committee](https://researchobject.github.io/ro2019/#program-committee) to review.

Feel free to respond to reviewers comments and to update the submission if needed. 

**Tip:** Anyone is welcome to add an informal review below using GitHub comments; as an author perhaps you would volunteer to review [one of the other open submissions](https://github.com/ResearchObject/ro2019/issues)? 

Reviewers, please copy this review form and add as a comment. You don't need to use this form if you are not assigned from the PC.

```markdown
## Quality of Writing
_Is the text easy to follow? Are core concepts defined or referenced? 
Is it clear what is the author's contribution?_

(delete as appropriate)
* excellent / good / fair / poor

## Research Object / Zenodo

_URL for a Research Object or Zenodo record provided?
   Guidelines <http://researchobject.org/ro2019/submitting> followed?
   Open format (e.g. HTML)?
   Sufficient metadata, e.g. links to software?
   Some form of Data Package provided?
   Add text below if you need to clarify your score._

(delete as appropriate)
* none (e.g. only abstract in easychair/github)
* basic (e.g. Zenodo with PDF and minimal metadata)
* sufficient (e.g. HTML, detailed Zenodo metadata)
* good (followed guidelines, demonstrating own format, related resources included, but some details missing)
* excellent (e.g. followed all guidelines, complete metadata or RO-like research data package, linked data, provenance)

## Overall evaluation
_Please provide a brief review, including a justification for your scores. 
Both score and  review text are required._

(delete as appropriate)
* strong reject
* reject
* weak reject
* borderline 
* weak accept
* accept
* strong accept
```

For confidential remarks or questions about the peer-review process, contact ro2019@easychair.org

**Comment by danielskatz** [comment]
As I created this on Overleaf, there wasn't a great way to make an html version, but I've now used htlatex to create one and added it to the zenodo deposit. (The addition of the html (and css) are the only changes from v1 to v2 in zenodo)

**Comment by ptsefton** [comment]
I will review

**Comment by ptsefton** [comment]
## Quality of Writing
_Is the text easy to follow? Are core concepts defined or referenced? 
Is it clear what is the author's contribution?_


* good 

## Research Object / Zenodo

_URL for a Research Object or Zenodo record provided?
   Guidelines <http://researchobject.org/ro2019/submitting> followed?
   Open format (e.g. HTML)?
   Sufficient metadata, e.g. links to software?
   Some form of Data Package provided?
   Add text below if you need to clarify your score._


* sufficient (e.g. HTML, detailed Zenodo metadata)

## Overall evaluation

This proposes a means of citing complex research objects. The abstract does
describe a method for citing complex research objects and their dependencies but
in the absence of supporting examples of the output or code to show how this
would be done (which could have been packaged with the abstract, but the Zenodo
object appears to me to be just the abstract) it is not possible to evaluate the
approach. The presentation at the workshop should include examples using actual
research objects.

There is second proposal to have an "Active Research Object" with methods like
get() and put(), this implies that there would need to a Research Object
operating environment, which I find it hard to imagine. My first reaction is
that I think that the idea violates one of the (implicit?) principles of
Research Objects - that they are _declaratively_ specified - yes they may be
actionable, but the environment in which actions take place is a separate
concern from the structure of a Research Object and the RO specification.
Interested to hear more.


* accept

**Comment by stain** [comment]
Reminder that review of this abstract is due tomorrow Friday 2019-07-26. 

We're looking for one more volunteer! Perhaps @rapw3k, @FarahZKhan or @ocorcho could have capacity..?

**Comment by stain** [comment]
Deadline is today - any volunteers from @ResearchObject/ro-crate team?

**Comment by stain** [comment]
## Quality of Writing

* excellent

The text is well formulated and well written, making the arguments easy to follow.

## Research Object / Zenodo

[x] URL for a Research Object or Zenodo record provided?
[x] Guidelines <http://researchobject.org/ro2019/submitting> followed?
[x] Open format (e.g. HTML)?
[ ] Sufficient metadata, e.g. links to software?
[ ] Some form of Data Package provided?

_Add text below if you need to clarify your score._

* basic (e.g. Zenodo with PDF and minimal metadata)

A Zenodo record is provided with both PDF and HTML, but the record has only basic metadata. Perhaps add the citations and references as "Related identifiers" in Zenodo metadata?

## Overall evaluation
_Please provide a brief review, including a justification for your scores. 
Both score and  review text are required._

* strong accept

This abstract highlights the issues on citing research object, and what lessons we can learn from software citation and data citation practices. 

An interesting take from the author is that ROs are kind of both data and software, and so while earlier citation practices have clearly separated the two, here a compromise is needed. In addition ROs are similar to complex software where individual referenced items also should get a transitive citation.

I think this abstract invites for a very exciting presentation and will seed fruitful discussion at the workshop,

My only criticism will be on the introduction of the concept  "Active Research Objects" - while this in theory could be expanded, it seems underdeveloped and don't seem to offer anything beyond usual CRUD operations as over HTTP and other Digital object proposals. It is also unclear how an Active RO (presumably with an API?) relates to RO as an archived data package that may reside in a passive repository.

**Comment by danielskatz** [comment]
Thanks to both reviewers!

**Comment by stain** [comment]
Dear @danielskatz:

I am pleased to say that, given the reviewer comments, your submission has been **accepted** for oral presentation at [RO2019](https://researchobject.github.io/ro2019/).

You are invited to present a _10 minute talk_, followed by joint Q&A at end of the session.

You are also welcome to bring along a poster for the informal RO2019 poster session (which may cover work not reflected in this submission).


**Note**: All RO2019 presenters must _register_ and _attend_ the workshop at [eScience 2019](https://escience2019.sdsc.edu/) - please take care that you [register](https://escience2019.sdsc.edu/registration) with the  **Conference & Workshop** option to join the RO2019 workshop on Tue 24 Sept 2019.

Registration fees applies. Note that the IEEE eScience _early-bird registration_ discount expires **this Monday** - although we are negotiating with the eScience organizers to possibly extend this for presenters. A [PhD and Early career grant](https://escience2019.sdsc.edu/grant) is also available.

**Comment by stain** [comment]
Dear @danielskatz  et al,

As an accepted author at the RO2019 workshop we would like to remind you that at least one of the authors must be **registered** and **attend** the workshop at IEEE eScience 2019.

Please indicate here if the intended speaker(s)  differ from your initial submission.


eScience registration is at: <https://escience2019.sdsc.edu/registration>


We are pleased to inform you that, following our request, the availability of the eScience **early bird discount** has been extended until Monday 5 August 2019.


To [register](https://escience2019.sdsc.edu/registration), please select the _"Conference & Workshops"_ option, as the RO2019 workshop is on the Tuesday.


As a presenter, make sure you select:

* **Type:** "PRESENTER: Conference & Workshops", 
* **Session:** Workshop
* **Paper Number:** RO-14
* **Paper title:** Citation and Research Objects: Toward Active Research Objects

(It is possible to do _"Add Additional Paper/Poster"_ if you have other accepted eScience contributions - note that you do NOT need to use this for any RO2019 posters).

We look forward to seeing you in San Diego!

-- 
Stian Soiland-Reyes
on behalf of the RO2019 chairs

**Comment by stain** [comment]
Dear @danielskatz 

We are looking forward to hearing your submission presented at the RO2019 workshop in San Diego next week!

You will find the slot for your talk RO-14 in the workshop schedule:
<http://researchobject.org/ro2019/schedule>

Please let us know if you require a different time slot, or the indicated speaker has changed.


## Tweets

Feel free to tweet before/during/after the workshop!

We will use the hashtags [#ResearchObjects](https://twitter.com/hashtag/ResearchObjects) [#eScience2019](https://twitter.com/hashtag/eScience2019) 
(plural s)


## Slides

If you are presenting slides, we would appreciate if you are able to upload them here:
<https://www.dropbox.com/request/B1EDF6bNOULm9wS5S7Z7>

Format can be html, pdf, pptx, odp (we can convert to PDF)

I understand you may not have your slides ready yet, but we would appreciate if they are uploaded *before* your session start.


If your slides are web-based or already on Zenodo,  submit their URL here:
<https://github.com/ResearchObject/ro2019/issues/new/choose>

The resolution of the projector is 1920x1080 (16:9 widescreen).

Tip: If you use Twitter, include `@YourUsername` in the footer!

After the workshop we will upload the slides to Zenodo as CC-BY, please let us know if you require your slides to not be made public. 


## Zenodo 

You may also want to update your Zenodo record to augment your paper/abstract with the slides as a PDF - the DOI links from the Schedule page always to go the latest Zenodo update.

We have noticed some uploads have a mismatch of the  author lists. This might be a good time to check the metadata: 
<http://researchobject.org/ro2019/proceedings>


## Posters 

As noted earlier, all accepted speakers are welcome to bring along posters for the "informal" poster session, even if  the poster is not directly related to the accepted talk.

The poster should however be relevant to the aims of the [RO2019 workshop](http://researchobject.org/ro2019/) and not be a pure commercial.

If you bring a poster, please use the 10:05-10:30 coffee break to hang it in the room.

Posters should be no larger than 35” (0.89m) wide by 48” (1.2 m) tall with portrait-style orientation. 

Poster presenters are welcomed to do a 2 minute lightning talk during the "unconference" session.


## Unconference and collaborative notes
  
We are welcoming suggestions for activities during the afternoon unconference session, e.g.:
lightning talks, posters, demos, breakouts, discussions

Please help add ideas, comments and suggestion in the _Collective notes for RO2019 workshop_ <https://s.apache.org/ro2019>

You may also use this document for adding URLs and questions during the presentation sessions.
